### PR TITLE
support static link feature

### PR DESCRIPTION
**Pull request by unship**

### CODE REVIEW

**Comment by emk** [comment]
Hello, thank you for the patch!

I notice that you haven't included any explanation of what this patch is trying to accomplish, or why it's the right solution. And the continuous integration checks have lots of failures (which may not be related to your change!). If you'd like me to consider merging this, please provide me with something that's easier for me to understand and easier for me to merge. Thank you!

**Comment by Bobo1239** [comment]
As far as I understand it, the PR adds a (non-default) feature `static-link` which skips the `pkg-config` check in `build.rs` and forces a build of the bundled uchardet which is then linked (instead of the version which is installed on the system).

Though I believe that `static-link` is not the right name here, because afaik the library is always statically linked (not sure though). Also, one would probably only use this feature when the system's uchardet is outdated. (I was in that situation once and thought about exactly the same solution 😄 )

The build failures should be unrelated because they don't test with the feature enabled. (Dunno if uchardet is provided in the CIs' environments.)

**Comment by unship** [comment]
yes it is always static-link, "static-link" is not right feature name (although  I think it is intuitive)

**Comment by emk** [comment]
Hello. Given the ongoing difficulties of statically-linking C++ dependencies into Rust crates, and the existence of a native Rust `chardet` library, I've decided to deprecate `uchardet` in favor of `chardet`. I'm really sorry for the inconvenience.

**Pull request closed without merging**
